### ISSUE TITLE
Clarification 

### ISSUE THREAD

**Issue by vinodkkurmi** [barebell/DA#1]
hi @barebell,  Is this paper accepted for ICML 
Simple Domain Adaptation with Class Prediction Uncertainty Alignment?
Because I coudn't find it in ICML webpage. Can you please share the source for the same. It will useful for us to cite. Thanks

**Comment by barebell** [comment]
This paper is a ICML poster and I checked the its state on the arxiv.org. The address is linked after the title. While, this paper seems to be appearing in ICPRAM according to the comments by the authors on the archives.org.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Vinod K Kurmi <notifications@github.com>
发送时间: Saturday, February 2, 2019 6:27:58 PM
收件人: barebell/DA
抄送: barebell; Mention
主题: [barebell/DA] Clarification (#1)


hi @barebell<https://github.com/barebell>, Is this paper accepted for ICML
Simple Domain Adaptation with Class Prediction Uncertainty Alignment?
Because I coudn't find it in ICML webpage. Can you please share the source for the same. It will useful for us to cite. Thanks

―

**Comment by barebell** [comment]
It’s the arxiv.org, not archived.org. Sorry for my IM😂.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 博轩 孙
发送时间: Saturday, February 2, 2019 7:06:03 PM
收件人: barebell/DA; barebell/DA
抄送: Mention
主题: Re: [barebell/DA] Clarification (#1)

This paper is a ICML poster and I checked the its state on the arxiv.org. The address is linked after the title. While, this paper seems to be appearing in ICPRAM according to the comments by the authors on the archives.org.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Vinod K Kurmi <notifications@github.com>
发送时间: Saturday, February 2, 2019 6:27:58 PM
收件人: barebell/DA
抄送: barebell; Mention
主题: [barebell/DA] Clarification (#1)


hi @barebell<https://github.com/barebell>, Is this paper accepted for ICML
Simple Domain Adaptation with Class Prediction Uncertainty Alignment?
Because I coudn't find it in ICML webpage. Can you please share the source for the same. It will useful for us to cite. Thanks
